services:
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ur_code_paste

  codebin:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: database